export { PostCard } from './ui/PostCard/PostCard'
export { PostCardMain } from './ui/PostCardMain/PostCardMain'
export { PostCardHeader } from './ui/PostCardHeader/PostCardHeader'
export { PostCardFooter } from './ui/PostCardFooter/PostCardFooter'
export { PostCardComents } from './ui/PostCardComments/PostCardComents'
export { PostCardAddComent } from './ui/PostCardAddComent/PostCardAddComent'